# Variable 'acr.password' was defined in the Variables tab
# Variable 'acr.username' was defined in the Variables tab
# Variable 'app.LASR-RTU_DB_URL' was defined in the Variables tab
# Variable 'app.port' was defined in the Variables tab
# Variable 'repocentral.UserName' was defined in the Variables tab
# Variable 'repocentral.UserPassword' was defined in the Variables tab
variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/master

  # - repository: GESP-BMIG
  #   type: git
  #   endpoint: GESP-CodeCloud-BMig-via-wj2374
  #   name: 21326-GESP/21326-GESP-BMIG

  # - repository: MyAzureReposGitRepository # In a different organization
  #   endpoint: MyAzureReposGitServiceConnection
  #   type: git
  #   name: OtherProject/MyAzureReposGitRepo

  # - repository: database
  #   endpoint: ACC-Azure-02 14155-ORS
  #   type: git
  #   name: 14155-ORS/ORS-database
jobs:

- job: Job_1
  displayName: Agent job 1
  pool:
#    vmImage: 'ubuntu-latest'  # Brings up a VM at runtime using the image.
    name:  21326agents        # Uses the devops agent already built.

  steps:
  - checkout: self
    clean: true
  
  # task1 - checkout gesp-bmig library
  - script:
      echo 'Cloning GESP/BMIG project from CodeCloud...'

      export https_proxy=proxy.conexus.svc.local:3128
    
      git clone -v https://wj2374:MzU4NDc0NjkwNDk5OoRkrOU11Mf6eC3WC3uVUju70pcd@codecloud.web.att.com/scm/st_gesp/bmig.git gesp_bmig

      cd gesp_bmig

      git checkout feature/maven-updates-and-dockerize  
  # end task1 - checkout gesp-bmig library

  # - checkout: GESP-BMIG
    # clean: true

  - task: Maven@3
    displayName: Build Maven Package of GESP-BMIG using pom file.
    inputs:
      # workingDirectory: gesp_bmig
      mavenPOMFile: gesp_bmig/$(BuildParameters.mavenPOMFile)
      goals: clean package
      options: --settings settings.xml # For debug, use -e -X
      publishJUnitResults: false

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: 21326-container-registry # A service connection to 9642 ACR

  - task: Docker@2
    displayName: Build GESP-BMIG Wildfly Docker Image and Push it to gesp-bmig repo in ACR
    inputs:
      command: buildAndPush
      repository: gesp-bmig  # Repo name created in containerRegistry or 21326 ACR
      dockerFile: gesp_bmig/Dockerfile
#      dockerFile: Dockerfile.WildFly-Nigel
      tags: |
        $(Build.BuildId)

#  - task: Docker@1
#    displayName: Build LASR-RTU Wildfly Docker Image
#    inputs:
#      azureSubscriptionEndpoint: arm-nprd-sc # Service connection name from Pipeline setting.
#      azureContainerRegistry: 9642devopsacr.azurecr.io
#      command: build
#      dockerFile: Dockerfile.WildFly
#      imageName: 9642devopsacr.azurecr.io/lasr-rtu:$(Build.BuildId)
#      buildContext: Docker
#
#  - task: Docker@1
#    displayName: Docker Push Current Image to ACR
#    inputs:
#      azureSubscriptionEndpoint: arm-nprd-sc  # Service connection name from Pipeline setting.
#      azureContainerRegistry: 9642devopsacr.azurecr.io
#      command: Push an image
#      imageName: 9642devopsacr.azurecr.io/lasr-rtu:$(Build.BuildId)
#      buildContext: '**'
#
#
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy: gesp-bmig-eastus2-nprd-appservice-02'
    inputs:
      ConnectedServiceName: 21326-NPRD-SP-SC # Service connection under SP 9642-LASR-RTU-sp-NONPROD
#      ConnectedServiceName: 9642-container-registry # This doesn't work.
      WebAppKind: webAppContainer
      WebAppName: gesp-bmig-eastus2-nprd-appservice-02
      DockerNamespace: 21326devopsacr.azurecr.io
      DockerRepository: gesp-bmig
      DockerImageTag: $(Build.BuildId)
#      StartupCommand: ' '
#      AppSettings: -WEBSITES_PORT 8080 -PORT 8080
#
  - task: AzureAppServiceManage@0
    displayName: Restart GESP-BMIG Web App
    inputs:
      ConnectedServiceName: 21326-NPRD-SP-SC # aaf0b6e-3667-4eeb-8d60-74cef2015f44
      Action: Restart Azure App Service
      WebAppName: gesp-bmig-eastus2-nprd-appservice-02

  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      containerRegistry: 21326-container-registry # A service connection to 9642 ACR

#
